### ISSUE TITLE
Type declarations for TypeScript is missing

### ISSUE THREAD

**Issue by Yrlish** [tsndr/cloudflare-worker-jwt#1]
TypeScript is complaining it cannot find any type declarations. I can use the declare module workaround described as one of the solutions in the picture below, but this will not provide any linting to the functions.

![image](https://user-images.githubusercontent.com/3358782/116778038-fa28c600-aa6f-11eb-941e-928222d44f1a.png)

**Comment by tsndr** [comment]
Sure since this library is written in JS, but feel free to make a PR to add TS support.

**Comment by tsndr** [comment]
Sure since this is written in JS there are no type declarations
