### ISSUE TITLE
Verify function

### ISSUE THREAD

**Issue by lesterchuakh** [tsndr/cloudflare-worker-jwt#14]
Hi,

Line 110 of the verify function uses the signing function to verify, is this correct?

Line 110        const res = await crypto.subtle.sign(importAlgorithm, key, this._utf8ToUint8Array(tokenParts.slice(0, 2).join('.')))

**Comment by tsndr** [comment]
[v1.3.0](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v1.3.0)

We happy now? :)

**Comment by lesterchuakh** [comment]
> [v1.3.1](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v1.3.1)
> 
> We happy now? :)

Yes! Happy camper now. =)
