### ISSUE TITLE
Can't verify external tokens

### ISSUE THREAD

**Issue by badoge** [tsndr/cloudflare-worker-jwt#15]
`jwt.verify` always returns false when I try to verify tokens I receive from Twitch.
Also when I try to send a request to the Twitch API it returns an error saying it could not verify the token generated by `jwt.sign`

I think Twitch is expecting a token signed with a base64 encoded secret but when I decode the tokens generated by `jwt.sign` it doesn't seem be using a base64 encoded secret.

**Comment by tsndr** [comment]
Should be fixed with [v1.3.0](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v1.3.0).
