### ISSUE TITLE
RS256 with jwk doesn't seem to work?

### ISSUE THREAD

**Issue by ash-hashtag** [tsndr/cloudflare-worker-jwt#18]
Unable to import RSA key with format raw

**Comment by mhamrah** [comment]
I'm also trying to use this library with RS256 keys from Auth0 on Clouldflare. I'm at a loss to know what I should pass as a secret in the jwt.verify method. Any assistance would be appreciated- I have the jwks info and the certificate, but nothing seems to work.

**Comment by mooreds** [comment]
If you want to use RS256 with JWKS, there's an example in the forum here: https://fusionauth.io/community/forum/topic/2494/how-do-i-verify-a-token-with-the-cloudflare-worker-jwt-library
