### ISSUE TITLE
Error on Node 16.17.0

### ISSUE THREAD

**Issue by sarmedrizvi** [tsndr/cloudflare-worker-jwt#19]
I'm trying to access this function on Node 16.17.0 `jwt.sign({ ...payload }, secret);`

<img width="564" alt="Screenshot 2022-08-27 at 12 19 56 AM" src="https://user-images.githubusercontent.com/40367136/186976521-30e51cb5-6536-4808-8cf8-f385384a9fe0.png">

**Comment by tsndr** [comment]
This library is intended for use with Cloudflare Workers and is built on top of [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto). Node.js uses its own internal [Crypto](https://nodejs.org/docs/latest-v16.x/api/crypto.html) module module instead and is therefore not compatible.
