### ISSUE TITLE
reminder about Date.now() on cloudflare worker

### ISSUE THREAD

**Issue by he-yang** [tsndr/cloudflare-worker-jwt#21]
While reading https://developers.cloudflare.com/workers/runtime-apis/web-standards/

it was noted that ```Date.now() returns the time of the last I/O; it does not advance during code execution.```

A reminder to consider this in your code.

**Comment by tsndr** [comment]
I don't think that it matters too much.

How else would we determine the current time otherwise?

**Comment by he-yang** [comment]
I was writting some scripts requires getting current time on Cloudflare worker, and noted this special information from offical documentation.

Havn't figured out any good solutions. Hope someone can provide nice alternative.

**Comment by tsndr** [comment]
I think it's very unlikely that this will become an issue, also there's not really another viable alternative.

@he-yang Thanks for the headsup :)
