### ISSUE TITLE
Explicitly state in the docs that SECRET should be base64-encoded

### ISSUE THREAD

**Issue by mliakos** [tsndr/cloudflare-worker-jwt#22]
I think it would be wise to state in the docs that the JWT SECRET should be base64 encoded. It's not mentioned anywhere, nor it's a standard practice AFAIK.

**Comment by tsndr** [comment]
Reverted to original behavior with v2.1.1

**Comment by mliakos** [comment]
Could be optional via parameters, though (i.e. `jwtEncoding`)
