### ISSUE TITLE
ERROR  SubtleCrypto not supported!

### ISSUE THREAD

**Issue by retuerto** [tsndr/cloudflare-worker-jwt#23]
When using jwt.decode() method

**Comment by retuerto** [comment]
And with jwt.verify aswell. Trying to deploy a nuxt3 app to cloudflare workers, and getting this error.

**Comment by tsndr** [comment]
This library relies on `window.crypto.subtle` to be available, which is definetly available withing workers.

https://github.com/tsndr/cloudflare-worker-jwt/blob/ec41207832e3407760ea2d3501607b8d7a856f80/src/index.ts#L1-L2

**Comment by retuerto** [comment]
ℹ Initializing prerenderer                                                                                                  nitro 18:44:26

 ERROR  SubtleCrypto not supported!                                                                                               18:44:27

  at Object.<anonymous> (node_modules/@tsndr/cloudflare-worker-jwt/index.js:5:11)
  at Module._compile (node:internal/modules/cjs/loader:1101:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async prerender (node_modules/nitropack/dist/shared/nitro.9c828268.mjs:2667:26)

**Comment by retuerto** [comment]
It seems to fail when I use cloudflare-worker-jwt in routes prerendered with nitro. I am checking nitro configuration to see if there is a way to disable certain routes or indicate external dependencies/libraries. Not an expert on this matter

**Comment by tsndr** [comment]
Let me know if you're able to find a solution and if there's anything I can do to add support for your use case.

**Comment by retuerto** [comment]
My concern is that during deployment to cloudflare, nitro server is prerendering (locally in node environment) a server middleware that I use to verify JWT tokens sent from the client. Since SubtleCrypto is not available, throws the error. The two options I see are:
One: disable the server middleware and do it directly in every final route. A possible temporary workaround
Two: Check nitro config to see if we can indicate as external library and not execute locally. Does it make sense?

Could you indicate me if option two makes sense? Would you be so kind as to check nitro config?

**Comment by tsndr** [comment]
Maybe try adding this to the top of your index file:

```js
const { subtle } = require('node:crypto').webcrypto
Object.defineProperty(global, 'crypto', {
    value: { subtle }
})
```

If this works, that will pretty much confirm your theory that it's being ran in a node environment.
