### ISSUE TITLE
Node support?

### ISSUE THREAD

**Issue by Zombobot1** [tsndr/cloudflare-worker-jwt#27]
Is it possible to add Node support? I have tests for workers code that run in node environment but I get this: ``` throw new Error('SubtleCrypto not supported!')```

I also saw this [issue](https://github.com/tsndr/cloudflare-worker-jwt/issues/23) and it seems like the same problem. However, this doesn't help:
```ts
import { webcrypto } from 'node:crypto'
Object.defineProperty(globalThis, 'crypto', {
  value: { subtle: webcrypto.subtle },
})
```

**Comment by lukasreinfurt** [comment]
For me, the code above works in a test if imported before importing cloudflare-worker-jwt

**Comment by Zombobot1** [comment]
I use node 18

**Comment by lukasreinfurt** [comment]
```js
import { webcrypto } from 'node:crypto'
Object.defineProperty(globalThis, 'crypto', {
  value: { subtle: webcrypto.subtle },
})

import { expect, describe, test } from 'vitest';
import JWTService from '@template-app/service-jwt'; //<-- Just a wrapper around cloudflare-worker-jwt

describe('When', () => {
	test('Then', async () => {
		const jwtService = new JWTService();
		const token = await jwtService.encode({ test: 123 }, 'secret');
		const valid = await jwtService.verify(token, 'secret');
		expect(valid).toBeTruthy();
		const decoded =  await jwtService.decode(token, 'secret');
		expect(decoded.payload.test).toEqual(123);
	});
});
```
Here is my working test code, just checked it with node 18, still works.

**Comment by Zombobot1** [comment]
This is my test file

```ts
import { webcrypto } from 'node:crypto'
Object.defineProperty(globalThis, 'crypto', {
  value: { subtle: webcrypto.subtle },
})
import jwt from '@tsndr/cloudflare-worker-jwt'
jwt.verify('', '')
```

This is my launch command
```"test:manual": "nodemon --exec 'node --experimental-specifier-resolution=node --loader ts-node/esm' ./testRua.test.ts"```

**Comment by Zombobot1** [comment]
Did you set ```environment: "miniflare",``` in ```vitest.config.ts```?

**Comment by lukasreinfurt** [comment]
I'm running my tests without a vitest.config at the moment. But with your test file I also get the error now

**Comment by tsndr** [comment]
For me this works for testing (on node 16 and 18):

https://github.com/tsndr/cloudflare-worker-jwt/blob/1bdbd0a5c5f92901913718ab24158a8bcacccf86/index.test.js#L1-L4
