### ISSUE TITLE
Couple feature requests

### ISSUE THREAD

**Issue by tyvdh** [tsndr/cloudflare-worker-jwt#3]
First off thank you so much for this library. You just single handedly shaved nearly 1MB off my build now that I can toss `jsonwebtoken`.

1. Option for outputting the payload during verify
```javascript
try {
  await JWT.verify(authToken, JWT_TOKEN)
  jwt = await JWT.decode(authToken)
} catch(err) {
  throw {status: 401, message: `Invalid or expired authorization token`}
}
```
INTO
```javascript
try {
  jwt = await JWT.verify(authToken, JWT_TOKEN)
} catch(err) {
  throw {status: 401, message: `Invalid or expired authorization token`}
}
```

2. Validate `exp` keys during verify

3. Support for Buffer secrets
```javascript
JWT.verify(authToken, Buffer.from(JWT_TOKEN, 'base64'))
```

4. Support for es6 import destructuring syntax
```javascript
import { verify } from '@tsndr/cloudflare-worker-jwt'
```

5. If you're feeling really ambitions support verifying complex JWSs like what is being sent back from the Android safetynet attestation. https://developer.android.com/training/safetynet/attestation 😬

**Comment by tsndr** [comment]
I'm glad you like my library and it's really cool to hear that you've been able to save space using it.

1. I think there's a slight misunderstanding regarding the functionality of the `verify` method. In my (slightly janky) documentation under `verify` it says:

```
Verifies the integrity of the token and returns a boolean value.
```

So in order to verify the signature, you should do something like this:

```js
try {
    if (!await JWT.verify(authToken, JWT_TOKEN))
        throw
    jwt = await JWT.decode(authToken)
} catch(err) {
    throw {status: 401, message: `Invalid or expired authorization token`}
}
```

Otherwise unverified payloads will be accepted by your script, which kind of defeats the purpose of having JWTs 😅

2. I'm not quite sure what you mean by `exp` keys, can you elaborate?

3. I'm not sure if this is really necessary, but I'll look into it.

4. I guess it doesn't hurt to support ES module syntax so I'll put it on my TODO list.

5. I think this might be beyond the scope of this library, but I'll look into it.

**Comment by tyvdh** [comment]
1. Oof. I'm dumb. Have updated on my end. I'm torn though on if modern programming and especially the way other JWT libraries work if it should be a boolean `false` or throw. Any other library I've used, especially if it's promisified would throw rather than return `false`. Something to think about and research maybe.

2. JWT is a whole [standard](https://tools.ietf.org/html/rfc7519) and `exp` is a timestamp claim for ensuring a token can be invalidated after `exp: {future date in seconds}`. Additionally another important one to validate is `nbf` which ensures a token cannot be used until a specific data. There are others but these two are the most widely used and critically important to verify. Additionally another important claim you should likely be setting if it's not already included in the payload is `iat` which is just the seconds date the token was generated. This is done by any other JWT library I've used and many folks will be relying on this claim being set. All of these can be set manually but many libraries set `iat` by default to `now`. Finally regardless of who sets these, if any time related claims are included they should be considered when asking if a token is valid.

3. Fair enough. Not a big deal especially if you'd just take a Buffer and string it. A lot of folks however with other libraries will be passing in Buffers so will make swapping out things like `jsonwebtoken` for your library easier.

4. 🙏 

5. Yeah probably. I have something working but I'm not very well versed in SubtleCrypto syntax so I'm a bit clueless if what I have is actually a secure method for verifying a SafetyNet token 😝 

Most of my feedback revolves around existing incumbent libraries and beefing up your feature parity and also ensuring folks aren't thinking your `verify` method is doing more than the `jsonwebtoken`s `verify` method is.

---

Here's the helper I'm using as a wrapper around your library. Could help with any future improvements or feel free to include it in the README or an examples just to guide people into the concept that this is not a method for method replacement for other JWT libraries.

```
import JWT from '@tsndr/cloudflare-worker-jwt'
import moment from 'moment'

export async function verify(token, secret) {
  const jwt = await JWT.decode(token)

  if (
    jwt?.nbf
    && moment.utc(jwt.nbf, 'X').isAfter()
  ) throw 'Token too early'

  if (
    jwt?.exp
    && moment.utc(jwt.exp, 'X').isBefore()
  ) throw 'Token too late'

  const isValid = await JWT.verify(token, secret)

  if (!isValid)
    throw 'Token is invalid'

  return jwt
}

export async function sign(payload, secret) {
  if (
    payload?.sub 
    && !payload?.iat
  ) payload.iat = moment.utc().format('X')

  return JWT.sign(payload, secret)
}
```

**Comment by tsndr** [comment]
1. No worries man. This project is only loosely inspired by the `jsonwebtoken` library and I'm not the biggest fan of using exceptions unless something really breaks to be honest, although this is a personal preference. To me an `if` is cleaner than a `try`-`catch`.

2. Oh you meant `expiry`, see I'm stupid too 😅. Obviously, this is something I should absolutely add and a huge oversight on my part. This goes right to the top of my TODO list and I'll try to add it later today.

3. Maybe I should add it. Options are good, right? 🤔

4. While I'm already in there, I might add it today as well.

Thank you for the workaround, even though it shouldn't be necessary anymore once I finished my work on`2.`.

**Comment by tsndr** [comment]
2. All done. Added `nbf` and `exp` claims. It will be available from `v1.1.0` onwards.

4. Still on the list ;)

**Comment by tyvdh** [comment]
So a really good reason to do a try-catch block vs true-false is that you can denote why the JWT is invalid which is important for delivering helpful feedback back to the user. Knowing if the secret, content, nbf, or exp were the culprit are all important items to denote. So unfortunately the update, while helpful, doesn't remove the need for maintaining my existing helper and initial validation of at least the date based scopes so I can help my users out with what the JWT error actually is. An expired JWT is a very different kind of error to a not before error.

**Comment by tsndr** [comment]
Since we've sorted everything out in discord I'm gonna go ahead and close this issue :)
