### ISSUE TITLE
Allow the passage of a specific `iat`

### ISSUE THREAD

**Issue by tyvdh** [tsndr/cloudflare-worker-jwt#32]
Currently you can't pass `iat` as a param as it's always set internally. There are cases when you want to replace a token or swap one out for another but want to keep the same `iat` param as the first. Currently this isn't possible but it should be.

https://github.com/tsndr/cloudflare-worker-jwt/blob/main/src/index.ts#L199

**Comment by tyvdh** [comment]
fwiw this should be true of any set parameters. Anywhere your library is automatically setting params we should be able to configure our own should we choose to.

**Comment by tsndr** [comment]
Added with [`v2.1.4'](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.1.4)
