### ISSUE TITLE
consider removing crypto check

### ISSUE THREAD

**Issue by xHyroM** [tsndr/cloudflare-worker-jwt#34]
We should remove 
https://github.com/tsndr/cloudflare-worker-jwt/blob/76b7fcef2707225c9214fcba0c4e8d6498039daa/src/index.ts#L1-L2

because when you're building app with Astro for example, it throws error its not supported.

**Comment by tsndr** [comment]
But it won't work anyway if Crypto Subtle isn't available, so what's the point in removing that check?

**Comment by xHyroM** [comment]
ah sorry and do you know why when I build the application it throws me that it is not supported? after all Cloudflare Page Functions should support crypto

**Comment by tsndr** [comment]
Most likely, your bundler is using Node.js.

**Comment by xHyroM** [comment]
im using Astro with cloudflare adapter
