### ISSUE TITLE
unable to get .verify() to work with RS256

### ISSUE THREAD

**Issue by mrturck** [tsndr/cloudflare-worker-jwt#38]
On jwt.io I can verify a token and a signature with the RS256 algorithm, but I get false when running .verify() here

**Comment by jamesmfinney93** [comment]
Hey! Did you find a solution to this?

**Comment by jilio** [comment]
I confirm this issue

**Comment by tsndr** [comment]
Sorry, but I can't really replicate the issue you're having. Can you provide more context?

![image](https://github.com/tsndr/cloudflare-worker-jwt/assets/2940127/37b1a97e-23c3-4424-b0cf-f0bbed70b47d)
