### ISSUE TITLE
unable to get .verify() to work

### ISSUE THREAD

**Issue by 2hmad** [tsndr/cloudflare-worker-jwt#41]
I get `TypeError: Failed to execute 'importKey' on 'SubtleCrypto': 2nd argument is not instance of ArrayBuffer, Buffer, TypedArray, or DataView.` error after upgrade my nodejs version from `18.12` to `18.17`

```js
const JWTService = {
  verify: async function verify(
    request: NextRequest,
  ): Promise<boolean> {
    const algorithm: JwtAlgorithm = 'ES384'
    const token = request.cookies.get('token')

    if (!token) return false

    return jwt.verify(token.value, atob(String(process.env.JWT_PUBLIC_KEY)), { algorithm })
  }
}
```

![image](https://github.com/tsndr/cloudflare-worker-jwt/assets/32125808/4fa99d89-5464-4b0b-a285-42e9866ca310)

**Comment by tsndr** [comment]
Are you within a Cloudflare Worker environment?
