### ISSUE TITLE
Can't use @ in payload

### ISSUE THREAD

**Issue by iosdeveloper** [tsndr/cloudflare-worker-jwt#48]
I found out the hard way that you can't use the `@` character in the payload.
The `sign` function will generate a valid token, but the `decode` function will return `null` and the `valid` function will be false (or throw `PARSE_ERROR`).
Using `encodeURIComponent` or `%40` instead will fix it, but it doesn't seem that one should have to encode every payload before passing it to `sign`.

edit: Using secret string, e.g. `423e72ec59e3735d6e0cd5ed16707ba87659ff9aa0b938228fbeda5594c82867`.

**Comment by tsndr** [comment]
Related to #49, and fixed with [`v2.3.0`](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.3.0).
