### ISSUE TITLE
[BUG] verify not working in 2.2.10

### ISSUE THREAD

**Issue by simcolin** [tsndr/cloudflare-worker-jwt#49]
Was using version 2.2.3, everything works fine

updated to 2.2.10 and now the most basic example is not working

```js
const token = await jwt.sign({ chroot: "chroot" }, jwtSecret);
console.log(await jwt.verify(token, jwtSecret)) // prints false
```

Tested locally with Node version 20.9.0 and deployed to cloudflare pages

If you need any more infos about the setup

**Comment by rmarscher** [comment]
I just noticed this too with trying to verify a supabase token using a string hs256 key. Maybe an issue with the base64 handling in the v2.0.8 refactor? Downgrading to 2.0.7 fixes it for me.

**Comment by tsndr** [comment]
Hey, thanks for letting me know, will do some testing myself and report back :)

**Comment by tsndr** [comment]
I've now created a test project:
https://github.com/tsndr/jwt-test

And when depoying this to Cloudflare Workers it runs without any issues.

Here's the result:

```json
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzAwMTM2NjE1fQ.buu44sYllJT8Q0P-aBxSl68zIj6ysPVmXmGvGJg4pZ0",
  "verified": true
}
```

If you can provide more context, so that I'm able to reproduce this error, I'll try to implement a fix.

**Comment by simcolin** [comment]
When I test your project (https://github.com/tsndr/jwt-test) it works 

But if I remove the `sub` property from the `jwt.sign` payload, its broken. `payload` becomes null and `verify` return false

Here is the full code
```js
const secret = 'super-secret'

const token = await jwt.sign({ more: '@test' }, secret)
console.log({ token }) // { token:  'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtb3JlIjoiQHRlc3QiLCJpYXQiOjE3MDAxNDExMTd9.vBZIxVkxvXdpNc9tfmXQUHCpcDuJSVoMBNN6MbgBl2k' }

const decoded = jwt.decode(token)
console.log({ decoded }) // { decoded: { header: null, payload: null } }

const verified = await jwt.verify(token, secret)
console.log({ verified }) // { verified: false }
```

So the `sub` property seems mandatory for some reason, and was not before.

**Comment by simcolin** [comment]
While doing some tests I found a new weird behaviour.

for some reason if payload is `{ sub: "test" }` the verification works
but if payload is `{ sub: 'chroot' }` the verification fails and decoded payload is null

**Comment by tsndr** [comment]
Got it, please try again with [`v2.3.0`](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.3.0) :)

**Comment by simcolin** [comment]
2.3.0 fixes the issue for me, I just tested a few different payloads and they don't seem to impact decode or impact in a bad way.

Thank you for the fix !
