### ISSUE TITLE
Crypto is not defined

### ISSUE THREAD

**Issue by RicardoViteriR** [tsndr/cloudflare-worker-jwt#5]
Hello, I am getting a 'crypto is not defined' when building with typescript. Any ideas on what may be the issue?

**Comment by Edjevw12** [comment]
Got the same problem... on a nextjs project.

We used the nextjs example:
https://github.com/vercel/examples/blob/main/edge-functions/jwt-authentication/lib/utils.ts



![image](https://user-images.githubusercontent.com/37038043/139803517-1b3fb846-3a4b-4b27-ae94-908a0bb5c5b8.png)

**Comment by tsndr** [comment]
This library depends on Crypto.subtle, which is only available in the browser and Cloudflare Workers, it's not compatible with node or other serverless offerings.

**Comment by RicardoViteriR** [comment]
Hi @tsndr, I am deploying to cloudflare workers.

**Comment by tsndr** [comment]
The only thing I can say is that for some reason the router can't find the global `crypto` object. Maybe compare your project to [cloudflare/worker-typescript-template](https://github.com/cloudflare/worker-typescript-template).
