### ISSUE TITLE
There is no possibility to modify header

### ISSUE THREAD

**Issue by step135** [tsndr/cloudflare-worker-jwt#51]
It is sometimes needed to add some parameters to the header, e.g. kid. I had to modify `sign` method to enable it. You should find some consistent solution as it is ugly to put another sometimes compulsory (fourth) parameter after options.

**Comment by Le0Developer** [comment]
The options argument accepts a [`header` field](https://github.com/tsndr/cloudflare-worker-jwt/blob/main/src/index.ts#L79).

So `await sign({hello: "world"}, "KEY", { header: { typ: "JWT", kid: "..." } })` should work
