### ISSUE TITLE
algo validation missing

### ISSUE THREAD

**Issue by Complexicon** [tsndr/cloudflare-worker-jwt#68]
hi i just noticed while looking at your code, which is very helpful for workers btw, that there is no validation if the token algo is the same as the one specified in `verify()` which i would expect around [here](https://github.com/tsndr/cloudflare-worker-jwt/blob/main/src/index.ts#L202). 

there is a nice writeup on the [auth0 site](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/#Meet-the--None--Algorithm) where they explain why this could be a critical security vuln. 

basically it boils down to the server checking the rs256 signature while an attacker sends a hs256 signature.

i could create a pull request to fix this if you want but it more or less boils down to `if (header.alg != options.alg) throw new Error('ALG_MISMATCH')`

**Comment by tsndr** [comment]
Should be fixed with [`v2.4.7`](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.4.7), please reopen otherwise :)
