### ISSUE TITLE
Feature request - clockTolerance

### ISSUE THREAD

**Issue by patryk-smc** [tsndr/cloudflare-worker-jwt#69]
Hi
thank you for creating this library. Is there any chance that you could add `clockTolerance` option from `jsonwebtoken` lib?

You can learn more here: https://www.npmjs.com/package/jsonwebtoken#:~:text=a%20value%20here-,clockTolerance,-%3A%20number%20of%20seconds

Thanks a lot

**Comment by tsndr** [comment]
Here you go [`v2.5.0`](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.5.0) ;)
