### ISSUE TITLE
Make verify to return the decoded token

### ISSUE THREAD

**Issue by Kikobeats** [tsndr/cloudflare-worker-jwt#76]
I noted `verify` is internally calling `decode`:

https://github.com/tsndr/cloudflare-worker-jwt/blob/main/src/index.ts#L210

In a user flow, normally you want to verify the code _before_ decoding it, in this way:

```ts
await verify(token, JWT_SECRET, { throwError: true });
return decode(token).payload;
```

That means the token is being decode two times. A more optimal API would be return the decode value from `verify`:

```ts
const { decoded } = await verify(token, JWT_SECRET, { throwError: true });
```

**Comment by tsndr** [comment]
As of [`v3.0.0`](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v3.0.0) `verify()` will now return the decoded payload instead of a boolean.
