### ISSUE TITLE
Why does this not work with normal nodejs?

### ISSUE THREAD

**Issue by RScrusoe** [tsndr/cloudflare-worker-jwt#77]
I am getting Subtle crypto not found error.
Why would this not work on nodejs? Any work around to make it work on nodejs as well?

**Comment by darzove** [comment]
My understanding is this is intended to work within the context of a cloudflare worker. If you're not familiar, here is the page for [runtime APIs](https://developers.cloudflare.com/workers/runtime-apis/) available within the worker.

Within the node ecosystem, I recommend using the classic [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken)
