### ISSUE TITLE
Verification result when the token is expired

### ISSUE THREAD

**Issue by naourass** [tsndr/cloudflare-worker-jwt#83]
I'm wondering what's the proper way to verify a token and get the decoded version even if it's expired. My current use case requires me to use some data inside the token object both when it's expired and when it's still active, as long as the token is _technically_ valid. The questions that come specifically to my mind are:
1. If I use `verify()` without `options.throwError` set to `true` and the token is expired but all the other factors (like the structure and signature) are valid, would the response be the decoded token object or `undefined`?
2. Alternatively, when `options.throwError` is set to `true` and an `EXPIRED` error is thrown, does this mean the token is technically valid but just the `exp` is inferior than now, or there could be other invalid things?

An example for how to correctly read the data inside the token object both when it's `valid+active` and `valid+expired` and handle both cases would be highly appreciated!

**PS**. sorry for mixing up the terms _valid_ and _expired_ but that's the best way I come up with to formulate my question.

**Comment by tsndr** [comment]
Using `decode()` you can always extract the header and payload from the token, regardless if it has expired or not.
